### ISSUE TITLE
Issue with wp-content/uploads directory

### ISSUE THREAD

**Issue by chood531** [codemyviews/vanilla-core#3] opened 2018-05-13 05:14 UTC
It seems there is an issue where all files in the `wp-content/uploads` directory get deleted automatically, every time I view an admin page or any page on the site.

Please note that this seems to only happen when we have this option un-checked in the Media Settings: https://d.pr/i/taSDth

This option stores all uploads in the `wp-content/uploads` directory and does not store the media files in sub folders based off of the the year/month they were uploaded.

When we are in the scenario, the theme core is deleting all uploaded files.

**Comment by ikoolik** [comment] 2018-05-16 15:41
The issue is fixed in v1.3.3

Please run `composer update` from the theme folder.
You might also want to update the `path` property in `config/log.php` file. The easiest option is to set it to `uploads_path('log')` instead of `wp_upload_dir('log')['path']`

**Closed as completed** 2018-05-16 15:42 UTC
